knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la navigation
    default_options:
        page_name: page                # Nom du paramètre de page dans l'URL
        sort_field_name: sort          # Nom du paramètre de tri dans l'URL
        sort_direction_name: direction # Nom du paramètre de direction dans l'URL
        distinct: true                 # Résultats distincts
        filter_field_name: filterField # Nom du paramètre de filtre dans l'URL
        filter_value_name: filterValue # Valeur du filtre dans l'URL
    template:
        pagination: 'pagination/pagination.html.twig'      # Template de pagination
        sortable: '@KnpPaginator/Pagination/bootstrap_v5_bi_sortable_link.html.twig' # Template pour les liens de tri
        filtration: '@KnpPaginator/Pagination/bootstrap_v5_filtration.html.twig'   # Template pour le filtrage 